config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  resources :experiences, only: [:index, :show, :new, :create] do
    resources :bookings, only: [:create]
    resources :reviews, only: [:index, :new, :create]
  end

  resources :reviews, only: [:show, :edit, :update, :destroy]
  resources :bookings, only: [:index, :update]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :experience
  belongs_to :user

  validates :experience, presence: true
  validates :user, presence: true
  validates :date, presence: true

  enum status: [ :pending, :accepted, :rejected, :archived ]
end

app/models/experience.rb
class Experience < ApplicationRecord
  belongs_to :user
  has_many_attached :photos
  has_many :bookings
  has_many :reviews, dependent: :destroy

  validates :title, presence: true
  validates :duration, presence: true
  validates :content, presence: true
  validates :location, presence: true
  validates :price, presence: true
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  include PgSearch::Model
  pg_search_scope :search_by_title_and_content,
  against: [ :title, :content ],
  using: {
    tsearch: { prefix: true } # <-- now `superman batm` will return something!
  }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :experience
  belongs_to :user

  validates :experience, presence: true
  validates :user, presence: true
  validates :content, presence: true
  validates :rating, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :experiences
  has_many :bookings
  has_many :reviews, through: :experiences
  has_many :bookings_as_guide, through: :experiences, source: :bookings

  has_one_attached :avatar
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?


  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :avatar])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :avatar])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[ show edit update destroy ]

  # GET /articles or /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1 or /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles or /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to article_url(@article), notice: "Article was successfully created." }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1 or /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to article_url(@article), notice: "Article was successfully updated." }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1 or /articles/1.json
  def destroy
    @article.destroy!

    respond_to do |format|
      format.html { redirect_to articles_url, notice: "Article was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def article_params
      params.require(:article).permit(:title, :body)
    end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @bookings = current_user.bookings
    @received_bookings = current_user.bookings_as_guide
  end

  def create
    # booking needs experience, user, status, start date
    @booking = Booking.new(booking_params)
    @booking.date = Date.parse(params[:booking][:date])
    @experience = Experience.find(params[:experience_id])
    @booking.user = current_user
    @booking.experience = @experience
    if @booking.save
      redirect_to bookings_path
    else
      render "#", status: :unprocessable_entity
    end
  end

  def update
    @received_booking = Booking.find(params[:id])
    if @received_booking.update(booking_params)
      redirect_to bookings_path
    else
      render "#", status: :unprocessable_entity
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:experience, :user, :status, :date)
  end
end

app/controllers/experiences_controller.rb
class ExperiencesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:index, :show]

  def index
    if params[:query].present?
      @experiences = Experience.search_by_title_and_content(params[:query])
    else
      @experiences = Experience.all
    end

    @markers = @experiences.geocoded.map do |experience|
      {
        lat: experience.latitude,
        lng: experience.longitude,
        info_window_html: render_to_string(partial: "info_window", locals: { experience: experience })
      }
    end
  end

  def show
    @experience = Experience.find(params[:id])
    @reviews = @experience.reviews
    @booking = Booking.new
    @review = Review.new
  end

  def new
    @experience = Experience.new
  end

  def create
    @experience = Experience.new(experience_params)
    @experience.user = current_user
    if @experience.save
      redirect_to @experience, notice: 'Experience was successfully created.'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def experience_params
    params.require(:experience).permit(:location, :title, :content, :duration, :price, photos: [])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @experience = Experience.all.sample
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_experience, only: %i[new create]

  def new
    # We need @restaurant in our `simple_form_for`
    @experience = Experience.find(params[:experience_id])
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.experience = @experience
    @review.user = current_user
    @booking = Booking.new
    if @review.save
      redirect_to experience_path(@experience)
    else
      render "experiences/show", status: :unprocessable_entity
    end
  end

  private

  def set_experience
    @experience = Experience.find(params[:experience_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @experiences = @user.experiences
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>">
  <p>
    <strong>Title:</strong>
    <%= article.title %>
  </p>

  <p>
    <strong>Body:</strong>
    <%= article.body %>
  </p>

</div>

app/views/articles/_form.html.erb
<%= simple_form_for(@article) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :body %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Show this article", @article %> |
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Articles</h1>

<div id="articles">
  <% @articles.each do |article| %>
    <%= render article %>
    <p>
      <%= link_to "Show this article", article %>
    </p>
  <% end %>
</div>

<%= link_to "New article", new_article_path %>

app/views/articles/new.html.erb
<h1>New article</h1>

<%= render "form", article: @article %>

<br>

<div>
  <%= link_to "Back to articles", articles_path %>
</div>

app/views/articles/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @article %>

<div>
  <%= link_to "Edit this article", edit_article_path(@article) %> |
  <%= link_to "Back to articles", articles_path %>

  <%= button_to "Destroy this article", @article, method: :delete %>
</div>

app/views/bookings/_accept_reject.html.erb
<div class="d-flex">
  <%= simple_form_for received_booking do |f| %>
    <%= f.input :status, as: :hidden, input_html: { value: 'accepted'} %>
    <%= f.submit 'Accept', class: 'lightgreen-btn me-2' %>
  <% end %>

  <%= simple_form_for received_booking do |f| %>
    <%= f.input :status, as: :hidden, input_html: { value: 'rejected'} %>
    <%= f.submit 'Reject', class:'lightred-btn' %>
  <% end %>
</div>

app/views/bookings/_create_booking.html.erb
<div class="container">
  <h3>Pick your Dates</h3>
  <%= simple_form_for [@experience, @booking] do |f| %>
    <%= f.input :date %>
    <%= f.submit %>
  <% end %>
  <h4>Price Breakdown</h4>
</div>

app/views/bookings/index.html.erb
<div class="main-container">
  <div class="booking-container">
    <% if @bookings.any? %>
      <div class="row justify-content-center">
        <div class="col-7">
          <h1 class="my-3">Bookings</h1>
          <% @bookings.each do |booking| %>
            <div class="card-product my-3">
              <% if booking.experience.photos.attached? %>
                <%= cl_image_tag booking.experience.photos.first.key %>
              <% else %>
                <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU', class: 'card-image' %>
              <% end %>
              <div class="card-product-infos d-flex justify-content-between">
                <div class="info-left">
                  <h2><strong><%= booking.experience.title %></strong></h2>
                  <p><i class="fa-solid fa-calendar-days"></i> <%= booking.date %></p>
                  <p><i class="fa-solid fa-clock"></i> <%= booking.experience.duration %> hours</p>
                  <p> Guide: <%= booking.experience.user.first_name %></p>
                </div>
                <div class="info-right">
                  <div class="status-<%= booking.status %>">
                    <p><strong><%= booking.status.capitalize %></strong></p>
                  </div>
                  <div class="product-price">
                    <p><strong><%= number_to_currency(booking.experience.price, precision: 0) %></strong></p>
                  </div>
                </div>
              </div>
              <%= link_to '', experience_path(booking.experience), class:"card-product-link" %>
            </div>
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="alert alert-primary mt-5" role="alert">
        You do not have any bookings
      </div>
    <% end %>
    <%# recived bookings section start here%>
    <% if @received_bookings.any? %>
      <div class="row justify-content-center">
        <div class="col-7">
          <h1 class="my-3">Received Bookings</h1>
          <% @received_bookings.each do |received_booking| %>
            <div class="card-product my-3">
              <%= cl_image_tag received_booking.experience.photos.first.key %>
              <div class="card-product-infos position-relative">
                <h2><strong><%= received_booking.experience.title %></strong></h2>
                <p><i class="fa-solid fa-calendar-days"></i> <%= received_booking.date %></p>
                <p><i class="fa-solid fa-clock"></i> <%= received_booking.experience.duration %></p>
                <p><strong>Status:</strong> <%= received_booking.status.capitalize %></p>
                <%# added accept/reject buttons %>
                <div class="info-right position-absolute">
                  <% if received_booking.status == "pending" %>
                    <%= render "bookings/accept_reject", received_booking: received_booking %>
                  <% else %>
                    <p class="mt-4"><strong>This booking has been "<%= received_booking.status %>"</strong></p>
                  <% end %>
                </div>
                <%# End of button form  %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
    <%= link_to "Back to Experiences", experiences_path, class:"lightpurple-btn button-center text-decoration-none mb-5" %>
  </div>
</div>

app/views/bookings/new.html.erb
<div class="container">
  <h3>Pick Your Dates</h3>
  <%# CALENDAR %>
  <%= simple_form_for [@experience, @booking] do |f| %>
    <%= f.input :date %>
    <%# Price breakdown %>
    <h4>Price Breakdown</h4>
    <div class="show-price">
      <p>Price</p>
      <%= @experience.price %>
      <p>Tax</p>
      <p>$10</p>
    </div>
    <%# Submit Booking %>
    <%= f.submit %>
  <% end %>
</div>

app/views/experiences/_form.html.erb
<!-- app/views/articles/_form.html.erb -->
<%= simple_form_for(experience) do |f| %>
  <!-- [...] -->
  <%= f.input :photo, as: :file %>
  <!-- [...] -->
<% end %>

app/views/experiences/_info_window.html.erb
<% if experience.photos.attached? %>
  <%= cl_image_tag experience.photos.to_a.first.key, class: 'card-image-map' %>
<% else %>
  <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU', class: 'card-image' %>
<% end %>
<h5 class="my-3"><%= experience.title %></h5>
<p><i class="fa-solid fa-location-dot"></i> <%= experience.location.capitalize %></p>
<p><i class="fa-solid fa-clock"></i> <%= experience.duration %> hours</p>

app/views/experiences/_map.html.erb
  
<div style="width: 100%; height: 600px;"
    class="map-body"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>"
    data-action="click->map#resize">
</div>

app/views/experiences/_review_form.erb
<%= simple_form_for [experience, review] do |f| %>
  <%= f.input :content, label: "Your Review" %>
  <%= f.input :rating, label: "Rating", as: :select, collection: 1..5 %>
  <%= f.submit "Submit Review", class: "btn btn-primary" %>
<% end %>

app/views/experiences/index.html.erb
<div class="container mt-4 mb-4 ">
  <div class="d-flex justify-content-center">
    <div class="header-item mx-3"><i class="fa-solid fa-mountain-sun fa-xl" style="color: #8356D1;"></i></div>
    <div class="header-item mx-3"><i class="fa-solid fa-umbrella-beach fa-xl" style="color: #8356D1;"></i></div>
    <div class="header-item mx-3"><i class="fa-solid fa-martini-glass-citrus fa-xl" style="color: #8356D1;"></i></div>
    <div class="header-item mx-3"><i class="fa-solid fa-dungeon fa-xl" style="color:#8356D1;"></i></div>
  </div>
</div>
<div class="cards-container">
  <div class="cards-container">
    <% if @experiences.any? %>
      <% @experiences.each do |experience| %>
        <div class="card-experience">
          <div class="image-container">
            <% if experience.photos.attached? %>
              <%= cl_image_tag experience.photos.to_a.first.key, class: 'card-image' %>
            <% else %>
              <%= image_tag 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTPQDYau3Hs4-xw1i8jVSUY4BlF4FLmg8lQqg&usqp=CAU', class: 'card-image' %>
            <% end %>
          </div>
          <div class="card-content">
            <h5 class="card-title mt-1"><%= experience.title %></h5>
            <p class="card-text-details"><%= experience.content %></p>
            <div class="d-flex">
              <% if experience.user.avatar.attached? %>
                <p><%= cl_image_tag experience.user.avatar.key, class: "avatar me-2" %></p>
              <% else %>
                <p><%= image_tag 'Defaultprofilepicture.png', class: "avatar me-2" %></p>
              <% end %>
              <p class="hosted-by"><%= experience.user.first_name %></p>
            </div>
            <p class="price"><%= experience.price.round %> USD</p>
          </div>
          <%= link_to '', experience_path(experience), class: 'card-experience-link position-absolute' %>
        </div>
      <% end %>
    <% else %>
      <em>Sorry, no experiences found.</em>
    <% end %>
  </div>
  <%# adding map %>
  <button type="button" class="map-button lightpurple-btn mb-4" data-bs-toggle="modal" data-bs-target="#exampleModal">
    Explore Map <i class="fa-regular fa-map"></i>
  </button>
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Explore Map <i class="fa-regular fa-map"></i></h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "map", locals: {markers: @markers}, class:"map-size" %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/experiences/show.html.erb
<%# Checks stylesheets 1. _user-host-pill and 2. _show-experiences %>
<div class="container">
  <%# <div class="experience-header"> %>
  <%# </div> %>
  <%# comment %>
  <div>
    <%= link_to 'Back to Experiences', experiences_path, class: "lightpurple-small-btn btn btn-secondary" %>
  </div>
  <div class="experience-images-header">
    <% if @experience.photos.count === 5 %>
      <div class="image-grid">
        <% @experience.photos.each_with_index do |photo, index| %>
          <div class="image-grid-item <%= "item#{index + 1}" if index > 0 %> <%= 'main' if index == 0 %>">
            <%= image_tag photo, class: "image-item" %>
          </div>
        <% end %>
      </div>
    <% elsif @experience.photos.count === 1 %>
      <div class="single-image">
        <%= image_tag @experience.photos.first %>
      </div>
    <% else %>
      <div class="single-image">
        <%= image_tag 'https://images.pexels.com/photos/20187381/pexels-photo-20187381/free-photo-of-sapporo-fushimi-inari-shrine-in-winter.jpeg?auto=compress&cs=tinysrgb&w=1260&h=750&dpr=1' %>
      </div>
    <% end %>
  </div>
</div>
</div>
<div style="display: flex" class="show-page-body">
  <div class="experience-details" style="flex: 6; padding-right: 20px;">
    <h1><%= @experience.title %></h1>
    <ul style="list-style-type: none; display: flex; gap: 10px;">
      <li><%=@experience.location%> • </li>
      <li><%=@experience.duration%>Days Duration • </li>
      <li>Experience Tag</li>
    </ul>
    <div class="experience-show-user">
      <h3 class="h3-show">About your guide</h3>
      <div class="user-host-pill grid-item">
        <% if @experience.user.avatar.attached? %>
          <p><%= cl_image_tag @experience.user.avatar.key, class: "avatar me-2" %></p>
        <% else %>
          <p><%= image_tag 'Defaultprofilepicture.png', class: "avatar me-2" %></p>
        <% end %>
        <div class="user-info">
          <h3><%= @experience.user.first_name %></h3>
          <p>Guide</p>
        </div>
        <div class="user-host-show-rating">
          <p>
            <% sum = 0.0 %>
            <% @reviews.each do |review| %>
              <% sum += review.rating %>
            <% end %>
            <% average = @reviews.size > 0 ? sum / @reviews.size : 0 %>
            <%= average.round(1) %>
          </p>
          <div class="stars">
            <% average.round.times do %>
              <i class="fa-solid fa-star"></i>
            <% end %>
          </div>
        </div>
        <%= link_to "", user_path(User.find(@experience.user_id)), class:"user-host-pill-link", target: "_blank" %>
      </div>
    </div>
    <div>
      <div>
        <h3 class="h3-show">Experience Higlights</h3>
      </div>
      <div>
        <ul class="experience-highlights">
          <li><%= raw "Explore the <strong>stunning</strong> landscapes of Japan's countryside, including majestic mountains and tranquil lakes." %></li>
          <li><%= raw "Immerse yourself in the <strong>rich culture</strong> with guided tours to ancient temples and local markets." %></li>
          <li><%= raw "Savor <strong>delicious</strong> local cuisine, with opportunities to try sushi-making and traditional tea ceremonies." %></li>
        </ul>
      </div>
      <div>
        <h3 class="h3-show">About your trip</h3>
      </div>
      <div>
        <p><%= @experience.content %></p>
      </div>
      <div data-controller="review">
        <%= link_to 'Add a review', '#', class: "lightpurple-small-btn btn btn-secondary mb-3", data: { action: "click->review#fire" } %>
        <div data-review-target="togglableElement" class="d-none">
          <%= render "experiences/review_form", experience: @experience, review: @review %>
        </div>
      </div>
    </div>
    <div class="container mt-3 h3-show">
      <h2>Reviews</h2>
      <% @reviews.each do |review| %>
        <div class="col-md-4 mb-4">
          <div class="card">
            <div class="card-body">
              <h5 class="card-text">Reviewer: <%= review.user.first_name %></h5>
              <h5 class="card-title"> <% review.rating.round.times do %>
                  <i class="fa-solid fa-star"></i>
                <% end %>
              </h5>
              <p class="card-text"><%= review.content %></p>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
  <div class="booking-form">
    <h3 class="my-3">Pick your Date</h3>
    <%= simple_form_for [@experience, @booking] do |f| %>
      <%= f.input :date,
            as: :string,
            input_html: { data: { controller: "datepicker" } } %>
      <h4>Price Breakdown</h4>
      <div class="price-details row">
        <div class="price-row">
          <span id="price-heading">Price</span>
          <span id="price-num">$<%= @experience.price.round %></span>
        </div>
        <div class="duration-row">
          <span id="duration-heading">Duration</span>
          <span id="duration-num"><%= @experience.duration %> Hours</span>
        </div>
        <div class="price-row subtotal">
          <span id="price-heading">Subtotal</span>
          <span id="price-num">$<%= @experience.price.round %></span>
        </div>
      </div>
      <div class="d-grid gap-2">
        <%= f.submit 'Book Now', class: 'btn mt-2 btn-primary' %>
      </div>
    <% end %>
  </div>
</div>
</div>
</div>
</div>

app/views/pages/home.html.erb
<%# <h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>
background image in body, header %>
<body style="background-image: url('https://images.pexels.com/photos/5845255/pexels-photo-5845255.jpeg')">
  <div class="home-background">
    <div class="home-text">
      <h1 id="header-first">Experience the World</h1>
      <h1 id="header-second">Through the Eyes of a Local</h1>
      <%= link_to experiences_path do %>
        <button class="btn btn-primary btn-lg" id="index">Start Exploring Now</button>
      <% end %>
    </div>
  </div>
</body>

app/views/reviews/new.html.erb
<h1>New review</h1>
<%= simple_form_for [@experience, @review] do |f| %>
  <%= f.input :content %>
  <%= f.submit "Submit review", class: "btn btn-primary" %>
<% end %>

app/views/shared/_filterbar.html.erb
<nav class="navbar navbar-light bg-light">
  <i class="fa-solid fa-mountain-sun" style="color: #B197FC;"></i>
  <i class="fa-solid fa-umbrella-beach" style="color: #B197FC;"></i>
  <i class="fa-solid fa-martini-glass-citrus" style="color: #B197FC;"></i>
  <i class="fa-solid fa-dungeon" style="color: #B197FC;"></i>
</nav>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
    <% end %>
    <div class="d-flex flex-column align-items-center">
      <div class="d-flex flex-row justify-content-center mt-3">
        <%= link_to 'Home', root_path, class: "header-item mx-3 fw-bold", style: "color: #808080; text-decoration: none;" %>
        <%= link_to 'All Experiences', experiences_path, class: "header-item mx-3 fw-bold", style: "color: #808080; text-decoration: none;" %>
        <% if user_signed_in? %>
          <%= link_to 'My Bookings', bookings_path, class: "header-item mx-3 fw-bold", style: "color: #808080; text-decoration: none;" %>
          <%= link_to 'My Profile', user_path(current_user), class: "mx-3 fw-bold", style: "color: #808080; text-decoration: none;" %>
        <% else %>
        <% end %>
        <%= link_to 'Offer your Experience', new_experience_path, class: "header-item mx-3 fw-bold", style: "color: #8356D1; text-decoration: none;" %>
      </div>

    <div class=" d-flex row justify-content-center mt-3 mb-3">
    <%= form_with url: experiences_path, method: :get, class: "d-flex" do %>
      <%= text_field_tag :query,
            params[:query],
            class: "form-control",
            placeholder: "Type a keyword"
        %>
        <button ><i class="fas fa-search no-border-radius"style="color: #8356D1"></i></button>
    <% end %>



</div>
    </div>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item dropdown">
            <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%#= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
              <% if current_user.avatar.attached? %>
                <%= image_tag current_user.avatar, class:"avatar", alt: "dropdown menu" %>
              <% else %>
                <%= image_tag 'https://res.cloudinary.com/djqladxhq/image/upload/v1723730530/x17umayb2am44f33ixtt.png', class:"avatar", alt: "dropdown menu" %>
              <% end %>
            </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link position-absolute mt-3" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>